# Generated by Django 5.2.7 on 2025-12-10 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_since_last_txn', models.FloatField()),
                ('channel', models.CharField(max_length=20)),
                ('merchant_category', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=5)),
                ('time_of_day', models.CharField(max_length=20)),
                ('day_of_week', models.CharField(max_length=10)),
                ('previous_24h_txns', models.IntegerField()),
                ('avg_amount_7d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chargeback_history', models.BooleanField()),
                ('prediction', models.IntegerField()),
                ('fraud_probability', models.FloatField()),
                ('ml_probability', models.FloatField()),
                ('rule_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
