from rest_framework import serializers

class FraudPredictionSerializer(serializers.Serializer):
    Time = serializers.FloatField(required=False)
    V1 = serializers.FloatField(required=False)
    V2 = serializers.FloatField(required=False)
    V3 = serializers.FloatField(required=False)
    V4 = serializers.FloatField(required=False)
    V5 = serializers.FloatField(required=False)
    V6 = serializers.FloatField(required=False)
    V7 = serializers.FloatField(required=False)
    V8 = serializers.FloatField(required=False)
    V9 = serializers.FloatField(required=False)
    V10 = serializers.FloatField(required=False)
    V11 = serializers.FloatField(required=False)
    V12 = serializers.FloatField(required=False)
    V13 = serializers.FloatField(required=False)
    V14 = serializers.FloatField(required=False)
    V15 = serializers.FloatField(required=False)
    V16 = serializers.FloatField(required=False)
    V17 = serializers.FloatField(required=False)
    V18 = serializers.FloatField(required=False)
    V19 = serializers.FloatField(required=False)
    V20 = serializers.FloatField(required=False)
    V21 = serializers.FloatField(required=False)
    V22 = serializers.FloatField(required=False)
    V23 = serializers.FloatField(required=False)
    V24 = serializers.FloatField(required=False)
    V25 = serializers.FloatField(required=False)
    V26 = serializers.FloatField(required=False)
    V27 = serializers.FloatField(required=False)
    V28 = serializers.FloatField(required=False)
    Amount = serializers.FloatField(required=False)
